name: Develop CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint-test:
    uses: ./.github/workflows/linting.yml

  notify:
    if: always()
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "🧪 Develop branch `${{ github.ref_name }}` CI complete. View run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
