name: Feature CI

on:
  push:
    branches: ["feature/**"]
  pull_request:
    branches: ["feature/**"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          pip install -r requirements.txt
          pip install pylint pytest
          pylint evolving_ideas
          pytest || echo "No tests yet"

  notify:
    if: always()
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "🧪 Feature branch `${{ github.ref_name }}` CI complete. View run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
