name: Push evolving-ideas docs to trivox-docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  push-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements-docs.txt

      - name: Build Sphinx docs with AutoAPI
        run: |
          sphinx-build -b html docs/source output/

      - name: Push to trivox-docs repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: trivox-io/trivox-docs
          publish_branch: main
          publish_dir: ./output
          destination_dir: evolving-ideas
          commit_message: "Update evolving-ideas built docs"
          keep_files: true
